###########
# site.title

title:    'Crispy Bread and Garlic Chicken - Taking Cars from Real Life into The Minecraft Overworld'
subtitle: 'CS 175: Project in AI (in Minecraft)'


#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md

theme: jekyll-theme-cayman
